# Generated by Django 5.0.4 on 2024-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0006_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operateur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
