# Generated by Django 5.0.4 on 2024-05-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0007_user_operateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='operateur',
            new_name='drone',
        ),
        migrations.AddField(
            model_name='user',
            name='dob_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dob_month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dob_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
