# Generated by Django 5.0.4 on 2024-05-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0008_rename_operateur_user_drone_user_dob_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dob_day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob_month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='drone',
        ),
    ]
