# Generated by Django 5.0.4 on 2024-05-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0011_rename_drone_user_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateur',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
