# Generated by Django 5.0.4 on 2024-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operateur', '0014_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='heure',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
